services:
  web: 
    build:
      context: app
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    restart: always
    ports:
      - '10020:8000'
